<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<AssemblyName>OniOnlvAisaLinkPatcher</AssemblyName>
	<GenerateAssemblyInfo>False</GenerateAssemblyInfo>
	<OutputType>Exe</OutputType>
	<TargetFramework>net20</TargetFramework>
	<LangVersion>13.0</LangVersion>
	<OutputPath>bin\$(Configuration)\</OutputPath>
	<EnableDefaultCompileItems>False</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
	<Compile Include="OniOnlvAisaLinkPatcher\Program.cs" />
	<PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net20" Version="1.0.3" PrivateAssets="All" />
  </ItemGroup>
</Project>
